include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Some additional lints we want to enforce
    always_declare_return_types: true
    cascade_invocations: true
    directives_ordering: true
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    use_build_context_synchronously: true
    use_super_parameters: true

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
