include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_positional_boolean_paramters: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    cascade_invocations: true
    directives_ordering: true
    flutter_style_todos: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_null_aware_method_calls: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    # unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_setters_to_change_properties: true
    # TODO: Since these lints are coming in flutter_lints v2.0.0,
    # remove this section when we update to Dart 2.17
    depend_on_referenced_packages: false # Temporarily disabled due to a false positive
    null_check_on_nullable_type_parameter: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_constructor_name: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
