name: hotdeals
description: A community-driven hot deals sharing app developed with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  expandable: ^5.0.1
  file_picker: ^4.1.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^11.2.0
  firebase_picture_uploader:
    path: lib/packages/flutter_firebase_picture_uploader
  firebase_storage: ^10.0.3
  flex_color_scheme: ^3.0.1
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.5.0
  flutter_facebook_auth: ^3.5.2
  flutter_localizations:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  google_nav_bar: ^5.0.5
  google_sign_in: ^5.1.1
  http: ^0.13.3
  image_picker: ^0.8.4+2
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  loggy: ^2.0.1
  material_floating_search_bar: ^0.3.4
  mime: ^1.0.0
  open_file: ^3.2.1
  overlay_support: ^1.2.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.5
  photo_view: ^0.13.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  timeago: ^3.1.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.12
  uuid: ^3.0.4
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/icons/
  uses-material-design: true
