name: hotdeals
description: A community-driven hot deals sharing app developed with Flutter.
publish_to: 'none'
repository: https://github.com/halildurmus/hotdeals
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  android_id: ^0.0.4
  badges: ^2.0.1
  better_open_file: ^3.6.3
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: ^5.0.1
  firebase_auth: ^3.3.11
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^13.0.0
  firebase_picture_uploader:
    path: packages/flutter_firebase_picture_uploader
  firebase_storage: ^10.0.3
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.3.1
  flutter_chat_ui: ^1.6.4
  flutter_facebook_auth: ^4.1.2
  flutter_local_notifications: ^11.0.1
  flutter_localizations:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: 2.0.0-dev.9
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.0.0
  freezed_annotation: ^2.1.0
  go_router: ^5.0.0
  google_nav_bar: ^5.0.5
  google_sign_in: ^5.1.1
  http: ^0.13.3
  image_picker: ^0.8.4+11
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  loggy: ^2.0.1
  material_floating_search_bar: ^0.3.4
  mime: ^1.0.0
  package_info_plus: ^1.4.3
  path: ^1.8.1
  path_provider: ^2.0.5
  photo_view: ^0.14.0
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  timeago: ^3.1.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.12
  uuid: ^3.0.4
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1

flutter:
  generate: true
  assets:
    - assets/icons/
  uses-material-design: true
