name: hotdeals
description: A community-driven hot deals sharing app developed with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.2.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  file_picker: ^4.0.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.6
  firebase_picture_uploader:
    path: lib/packages/flutter_firebase_picture_uploader
  firebase_storage: ^10.0.3
  flex_color_scheme: ^3.0.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.3.2
  flutter_facebook_auth: ^3.5.0
  flutter_localizations:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  get_it: ^7.1.3
  google_nav_bar: ^5.0.3
  google_sign_in: ^5.0.2
  http: ^0.13.1
  image_picker: ^0.8.4
  line_icons: ^2.0.1
  material_floating_search_bar: ^0.3.4
  mime: ^1.0.0
  open_file: ^3.2.1
  overlay_support: ^1.2.1
  path_provider: ^2.0.3
  photo_view: ^0.12.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  timeago: ^3.0.2
  transparent_image: ^2.0.0
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_generator: ^0.2.0+0

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
