name: hotdeals
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^2.2.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dash_chat:
    path: lib/packages/chat
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.2
  firebase_picture_uploader:
    path: lib/packages/flutter_firebase_picture_uploader
  firebase_storage: ^8.1.0
  flex_color_scheme: ^3.0.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  get_it: ^7.1.3
  google_nav_bar: ^5.0.3
  google_sign_in: ^5.0.2
  http: ^0.13.1
  image_picker: ^0.7.5+3
  line_icons: ^2.0.1
  material_floating_search_bar: ^0.3.4
  overlay_support: ^1.2.1
  path_provider: ^2.0.1
  #photo_view: ^0.11.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  timeago: ^3.0.2
  transparent_image: ^2.0.0
  url_launcher: ^6.0.6
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
  uses-material-design: true