name: firebase_picture_uploader
description: Picture upload widget which helps selecting and uploading one or multiple images to firebase storage.
version: 1.2.3
homepage: https://github.com/Rodiii/flutter_firebase_picture_uploader
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  image: ^3.0.5
  image_picker: ^0.8.4+2
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
